#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch case.foam 

# Create motion files
runApplication -s createMotion python3 DTC_PointGen.ipynb

mkdir -p constant/triSurface

# copy DTC hull surface from resources folder
cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/DTC-scaled.stl.gz \
    constant/triSurface/

runApplication surfaceFeatureExtract

runApplication blockMesh

for i in 1 2 3 4 5 6
do
    runApplication -s "$i" \
        topoSet -dict system/topoSetDict.${i}

    runApplication -s "$i" \
        refineMesh -dict system/refineMeshDict -overwrite
done

runApplication -s forSnappyHexMesh decomposePar # decompose to run snappyHexMesh in parallel
runParallel snappyHexMesh -overwrite
runParallel redistributePar -reconstruct -constant -overwrite # (not work in OF10)
rm -rf processor* # clean decomposed mesh not to interfere with interFoam decomposition
runApplication checkMesh -allGeometry -allTopology #-writeAllFields #-writeSets vtk

restore0Dir
runApplication setFields


runParallel -s decompose redistributePar -decompose
runParallel renumberMesh -overwrite

# runParallel moveDynamicMesh # do only mesh motion, 
# # need to comment out the force function in system/controlDict
# # adjust deltaT and maxDeltaT in system/controlDict 

runParallel $(getApplication)


runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
